name: Mutagen Patch

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install esp_tool
        run: pip install git+https://github.com/matortheeternal/esp_tool.git

      - name: Run patch script
        run: python mutagen_patch.py

      - name: Commit patched ESP
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Patch output.esp"
          file_pattern: output.esp
